In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
#x_train=
#y_train=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/trn01crd.csv',header=None)
#x_test=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/tst01rss.csv',header=None)
#y_test=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/tst01crd.csv',header=None)

In [ ]:
#concatenating the test data files of 6 months
'''x_ts1=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/tst01rss.csv',header=None)
y_ts1=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/tst01crd.csv',header=None)

for x in range(1,6):
  if(x>9):
    x_ts=x_ts.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/tst"+str(x)+"rss.csv",header=None))
    y_ts=y_ts.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/tst"+str(x)+"crd.csv",header=None))
  else:
    x_ts=x_ts.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/tst0"+str(x)+"rss.csv",header=None))
    y_ts=y_ts.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/tst0"+str(x)+"crd.csv",header=None))'''

In [ ]:

x_tr1=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/trn01rss.csv',header=None)#first month
y_tr1=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/trn01crd.csv',header=None)#first month
#concatenating the train data files of 14 months
x_tr=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/trn02rss.csv',header=None)
y_tr=pd.read_csv('/content/drive/MyDrive/Localisation_models/data1/01/trn02crd.csv',header=None)
for x in range(3,16):
  if(x>9):
    x_tr=x_tr.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/trn"+str(x)+"rss.csv",header=None))
    y_tr=y_tr.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/trn"+str(x)+"crd.csv",header=None))
  else:
    x_tr=x_tr.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/trn0"+str(x)+"rss.csv",header=None))
    y_tr=y_tr.append(pd.read_csv("/content/drive/MyDrive/Localisation_models/data1/01/trn0"+str(x)+"crd.csv",header=None))

In [ ]:
print(y_tr[0].max())
print(y_tr[0].min())
print(y_tr[1].max())
print(y_tr[1].min())
print(y_tr[0].var())
print(y_tr[1].var())

12.91385188
4.1347719
29.21654402
16.69981527
12.84696734178349
16.787905675947762


In [ ]:
print(x_tr.shape)
print(y_tr.shape)

(8064, 620)
(8064, 3)


In [ ]:
#x_train.head()
#y_train.head()
#x_test.head()
#y_test.head()


0          1  2
0  12.913852  29.216544  3
1  12.913852  29.216544  3
2  12.913852  29.216544  3
3  12.913852  29.216544  3
4  12.913852  29.216544  3

In [ ]:
x_tr=x_tr.to_numpy()


In [ ]:
#x_test=x_test.to_numpy()
y_tr=y_tr.to_numpy()
#y_test=y_test.to_numpy()


In [ ]:
x_tr1=x_tr1.to_numpy()
y_tr1=y_tr1.to_numpy()

In [ ]:
x_ts=x_ts.to_numpy()
y_ts=y_ts.to_numpy()
y_ts=y_ts[:,0:2]


In [ ]:
y_train[0:5,]

array([[12.91385188, 29.21654402,  3.        ],
       [12.91385188, 29.21654402,  3.        ],
       [12.91385188, 29.21654402,  3.        ],
       [12.91385188, 29.21654402,  3.        ],
       [12.91385188, 29.21654402,  3.        ]])

In [ ]:
y_tr=y_tr[:,0:2]

In [ ]:
y_tr1=y_tr1[:,0:2]

In [ ]:
y_test=y_test[:,0:2]

In [ ]:
y_tr[0:5,]

array([[12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402]])

In [ ]:
scaler = MinMaxScaler()
x_tr = scaler.fit_transform(x_tr)

In [ ]:
x_test=scaler.fit_transform(x_test)

In [ ]:
x_tr1=scaler.fit_transform(x_tr1)

In [ ]:
#KNN regressor fitted on training data of 1 month and tested on other 14 months
for x in range (1,7):
   neigh = KNeighborsRegressor(n_neighbors=x,weights='distance',algorithm='kd_tree')
   neigh.fit(x_tr1,y_tr1)
   y_pred=neigh.predict(x_tr)
   print("localisation error for k value %f is %f "%(x,localization_error(y_pred,y_tr)))

localisation error for k value 1.000000 is 3.364800 
localisation error for k value 2.000000 is 3.144244 
localisation error for k value 3.000000 is 3.074243 
localisation error for k value 4.000000 is 3.039011 
localisation error for k value 5.000000 is 3.001448 
localisation error for k value 6.000000 is 2.973983 


In [ ]:
x=7
print("it is %u %f"%(x,9))

it is 7 9.000000


In [ ]:
y_pred=neigh.predict(x_test)

In [ ]:
y_pred[0:20,]

array([[12.91385188, 27.78564691],
       [ 6.76211023, 28.14658687],
       [12.03579013, 27.42931594],
       [12.03472907, 28.50031265],
       [12.91385188, 27.78430612],
       [ 8.52934389, 24.92731898],
       [ 7.6453178 , 28.14482923],
       [ 4.1347719 , 28.85948176],
       [ 7.64740603, 27.42952422],
       [ 7.64379531, 28.14291961],
       [ 7.64067153, 27.78555171],
       [ 7.64102552, 28.14346002],
       [ 6.76454472, 27.42860517],
       [ 5.00479178, 26.70619475],
       [ 6.76460017, 27.78573785],
       [ 5.01414112, 26.35676792],
       [ 7.64636137, 27.7858736 ],
       [ 4.1347719 , 26.35536089],
       [12.91385188, 27.78813481],
       [ 6.76715254, 27.42772007]])

In [ ]:
y_test[0:20]

array([[12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [12.91385188, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 8.52431189, 29.21654402],
       [ 4.1347719 , 29.21654402],
       [ 4.1347719 , 29.21654402],
       [ 4.1347719 , 29.21654402],
       [ 4.1347719 , 29.21654402],
       [ 4.1347719 , 29.21654402],
       [ 4.1347719 , 29.21654402],
       [12.91385188, 27.42843992],
       [12.91385188, 27.42843992]])

In [ ]:
from numpy import sqrt, square, sum
def localization_error(prediction, truth):
    
    l=prediction.shape[0]
    x, y  = prediction[:,0], prediction[:,1]
    x0, y0 = truth[:,0], truth[:,1]
    error = sqrt(square(x - x0) + square(y - y0))
    return error.sum()/l

In [ ]:
a1=np.array([[1,2],[1,2]])
a2=np.array([[3,4],[6,7]])
print(localization_error(a1,a2))

4.949747468305833


In [ ]:
print(localization_error(y_pred,y_test))
#from sklearn.metrics import mean_squared_error
#print(mean_squared_error(y_test, y_pred))

3.0747893101610444


In [ ]:
x_train[0:5,]

array([[0.02564103, 0.17346939, 0.13333333, ..., 0.        , 0.        ,
        0.        ],
       [0.01025641, 0.15816327, 0.14358974, ..., 0.        , 0.        ,
        0.        ],
       [0.03589744, 0.16326531, 0.13846154, ..., 0.        , 0.        ,
        0.        ],
       [0.02564103, 0.16836735, 0.14871795, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.16326531, 0.13846154, ..., 0.        , 0.        ,
        0.        ]])